### ISSUE TITLE
HOW TO FIND FACTORAIL IS MISSING IN C FOLDER

### ISSUE THREAD

**Issue by onemriganka** [Xtha-Sunil/Class12-NEB#37]
THIS REPO IS AMAZING FOR THE STUDENTS. SO ADDING FACTORIAL CODE WILL BE VERY HELP FULL FOR THE STUDENTS

**Comment by onemriganka** [comment]
/ ATTEMPTED #37

**Comment by LuluW8071** [comment]
#38
